[package]
name = "parse-json"
version = "1.0.0"
publish = false
edition = "2018"

[dependencies]
hyper = "0.14.10"
hyper-tls = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
